const resList = [
  {
    id: "1",
    name: "Biryani Express",
    imageId: "https://img.freepik.com/free-photo/biryani-rice-with-chicken-indian-food_1150-26870.jpg",
    avgRating: "4.4",
    cuisine: ["Biryani", "Mughlai"],
    deliveryTime: "30 mins",
  },
  {
    id: "2",
    name: "Pizza Mania",
    imageId: "https://img.freepik.com/free-photo/delicious-fresh-pizza_144627-26418.jpg",
    avgRating: "4.1",
    cuisine: ["Pizza", "Italian", "Fast Food"],
    deliveryTime: "25 mins",
  },
  {
    id: "3",
    name: "Veg Delight",
    imageId: "https://img.freepik.com/free-photo/vegetarian-indian-food-thali_55610-2761.jpg",
    avgRating: "3.5",
    cuisine: ["North Indian", "Thali", "Healthy"],
    deliveryTime: "20 mins",
  },
  {
    id: "4",
    name: "Chinese Wok",
    imageId: "https://img.freepik.com/free-photo/asian-noodles-with-chicken-vegetables-wok_2829-19708.jpg",
    avgRating: "4",
    cuisine: ["Chinese", "Asian"],
    deliveryTime: "35 mins",
  },
  {
    id: "5",
    name: "Sweet Tooth",
    imageId: "https://img.freepik.com/free-photo/indian-traditional-sweets-arrangement_23-2148729386.jpg",
    avgRating: "4.5",
    cuisine: ["Desserts", "Bakery", "Sweets"],
    deliveryTime: "15 mins",
  },
  {
    id: "6",
    name: "Tandoori Nights",
    imageId: "https://img.freepik.com/free-photo/grilled-chicken-served-with-vegetables_140725-4714.jpg",
    avgRating: "4.3",
    cuisine: ["Tandoori", "Barbecue"],
    deliveryTime: "28 mins",
  },
  {
    id: "7",
    name: "Bombay Sandwich Co.",
    imageId: "https://img.freepik.com/free-photo/top-view-sandwich-with-fried-potatoes_23-2148570303.jpg",
    avgRating: "4.0",
    cuisine: ["Street Food", "Snacks"],
    deliveryTime: "18 mins",
  },
  {
    id: "8",
    name: "South Spice",
    imageId: "https://img.freepik.com/free-photo/south-indian-food_74190-4993.jpg",
    avgRating: "4",
    cuisine: ["South Indian", "Dosa", "Idli"],
    deliveryTime: "22 mins",
  },
  {
    id: "9",
    name: "The Salad Bowl",
    imageId: "https://img.freepik.com/free-photo/fresh-vegetable-salad-plate_144627-5420.jpg",
    avgRating: "3.8",
    cuisine: ["Salads", "Healthy", "Vegan"],
    deliveryTime: "15 mins",
  },
  {
    id: "10",
    name: "Roll Nation",
    imageId: "https://img.freepik.com/free-photo/chicken-kathi-rolls-served-plate_466689-74157.jpg",
    avgRating: "3.1",
    cuisine: ["Rolls", "Snacks"],
    deliveryTime: "27 mins",
  }
];
export default resList


